### ISSUE TITLE
Most of the covers not loading

### ISSUE THREAD

**Issue by FiliCZ** [marcussacana/VNDB-Extender-2020#7]
Don't know what Async does but I tried it both on and off and it still doesn't work.
![list](https://i.imgur.com/591klLj.png)

**Comment by marcussacana** [comment]
What browser?
Also, what version of the extension are you using?
If possible send a screenshot of the console output in the element inspector of your browser.

**Comment by FiliCZ** [comment]
Ok I just figured it out. Apparently in the extension setting only the main site was allowed, not the query.
![settings](https://i.imgur.com/vp2DVVc.png)
Don't know why that caused it to work just sometimes but it looks like it works fine now.

By the way there is a bug where although the "Disable tooltip" check box works fine and it remembers it's state after refresh, the actual function doesn't. What I mean by that is when I disable tooltips and refresh the page, the tooltips are back even though the check box is still checked.

**Comment by imKota** [comment]
@marcussacana +1
> If possible send a screenshot of the console output in the element inspector of your browser.

![image](https://user-images.githubusercontent.com/24241471/88722716-61f06000-d130-11ea-8c84-5c3c6d01cade.png)
![image](https://user-images.githubusercontent.com/24241471/88722739-6c125e80-d130-11ea-85a6-fc5e81dd94ee.png)

**Comment by marcussacana** [comment]
@imKota Check your version of the extension and the permissions, see if are everything allowed.
Also, what is your browser and their version?

**Comment by marcussacana** [comment]
I did a update, but not sure if that will fix it.

**Comment by imKota** [comment]
> @imKota Check your version of the extension and the permissions, see if are everything allowed.
> Also, what is your browser and their version?

Chrome 84.0.4147.105
everything allowed
![image](https://user-images.githubusercontent.com/24241471/88779537-9432a980-d192-11ea-8841-68fefa1623e5.png)

**Comment by imKota** [comment]
> I did a update, but not sure if that will fix it.

Not working 

![image](https://user-images.githubusercontent.com/24241471/88779839-e07de980-d192-11ea-933d-2b27cbbdc0d6.png)
![image](https://user-images.githubusercontent.com/24241471/88779869-e70c6100-d192-11ea-892b-e62c7e6ef1c7.png)

![image](https://user-images.githubusercontent.com/24241471/88779922-f8ee0400-d192-11ea-9f19-b9ed4544944c.png)
![image](https://user-images.githubusercontent.com/24241471/88779949-ff7c7b80-d192-11ea-9093-40d2bf5f6a56.png)

![image](https://user-images.githubusercontent.com/24241471/88779974-05725c80-d193-11ea-918f-b6939b808c61.png)

**Comment by marcussacana** [comment]
I really don't wanna support the chrome because the google ask for money to create a extension.
That said, probabbly the chrome is just ignoring the CSP changes by the unsigned extension maybe?
I can't do nothing about that probabbly, The code is working fine in the opera and msedge after all.
But maybe there are a alternative to you, is to use a secondary extension to disable the CSP in your browser.
But a warning, the CSP is a very important security feature to your browser, if you just left disable you can be vulnerable about your saved password and cookies.
3 Alternatives of those extensions, check if any of then allow disable only to one site, then left the query.vndb.org without protection.
https://chrome.google.com/webstore/detail/csp-disable-devtool/jffkjeddepiobnllominfajpefpcllka
https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden
https://chrome.google.com/webstore/detail/csp-disabler-for-develope/dmfdjjpckijmdclllmhpjegajihkiiid
The best alternative is forget this browser :+1: I dislike the google after all.
That said I know is hard to just ask someone change the browser because of a single extension.
But that is really what looks better to me personally, you can just export and import your favorites, the only problem is the saved passwords.
Anyway in your case @imKota this is your problem, the chrome.

I almost forget, you can too just disable the Query feature of the VNDB Extender, change this line of the code
https://github.com/marcussacana/VNDB-Extender-2020/blob/e36c79b45bb965f3113c4cad4fb1b702a7da56ab/scripts/Query.js#L72
change the `true` to `false` and that should work to you, probabbly, maybe, not sure.
Can looks strange, why the extension works with you changing that?
Basically the Query mode is a major otimization to the data loading of the visual novels.
Without this feature the extension can works fine but you will increase many times the cache size usage of the extension.
Also will load more slow, maybe with some hangs, and this will increase the request to the vndb site, this mean your IP can be temporally banned like in the old extension if you open many tabs.

**Comment by marcussacana** [comment]
AFK, Closing for now, if What I said don't fix just say
